<?php

use Illuminate\Database\Seeder;
use App\Modulo;

class ModulosSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    $modulos = collect(
      [
        ['sku_grupo' => 'ACJAB-01', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Vertical', 'consecutivo' => 1],
        ['sku_grupo' => 'ACJAB-02', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Vertical Y 6 Repisas', 'consecutivo' => 2],
        ['sku_grupo' => 'ACJAB-03', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Divisiones Vertical', 'consecutivo' => 3],
        ['sku_grupo' => 'ACJAB-04', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 3 Divisiones Vertical', 'consecutivo' => 4],
        ['sku_grupo' => 'ACJAB-05', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 4 Divisiones Vertical', 'consecutivo' => 5],
        ['sku_grupo' => 'ACJAB-06', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 5 Divisiones Vertical', 'consecutivo' => 6],
        ['sku_grupo' => 'ACJAB-07', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 5 Divisiones Vertical Asimetricos', 'consecutivo' => 7],
        ['sku_grupo' => 'ACJAB-08', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 5 Repisas', 'consecutivo' => 8],
        ['sku_grupo' => 'ACJAB-09', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Repisas', 'consecutivo' => 9],
        ['sku_grupo' => 'ACJAB-10', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Vertical Y 1 Repisa', 'consecutivo' => 10],
        ['sku_grupo' => 'ACJGV-06', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 53, 'nombre' => '1 Gaveta', 'consecutivo' => 6],
        ['sku_grupo' => 'ACJPT-01', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '1 Puerta Derecha', 'consecutivo' => 1],
        ['sku_grupo' => 'ACJPT-02', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '1 Puerta Izquierda', 'consecutivo' => 2],
        ['sku_grupo' => 'ACJPT-03', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '1 Puerta Horizontal Apertura Inferior', 'consecutivo' => 3],
        ['sku_grupo' => 'ACJPT-04', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '1 Puerta Horizontal Apertura Superior', 'consecutivo' => 4],
        ['sku_grupo' => 'ACJPT-05', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '2 Puertas', 'consecutivo' => 5],
        ['sku_grupo' => 'ACJPT-06', 'tipo_id' => 5, 'subtipo_id' => 15, 'categoria_id' => 55, 'nombre' => '2 Puertas Derecha Supe/Infe Con 8 Repisas', 'consecutivo' => 6],
        ['sku_grupo' => 'CAEAB-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Y 2 Repisas', 'consecutivo' => 1],
        ['sku_grupo' => 'CAEAB-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Repisa', 'consecutivo' => 2],
        ['sku_grupo' => 'CAEAB-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Divisiones Y 3 Repisas', 'consecutivo' => 3],
        ['sku_grupo' => 'CAECM-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 1],
        ['sku_grupo' => 'CAECM-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 56, 'nombre' => 'Panel Canteado', 'consecutivo' => 2],
        ['sku_grupo' => 'CAECM-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 56, 'nombre' => 'Panel Cierre', 'consecutivo' => 3],
        ['sku_grupo' => 'CAECM-04', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 56, 'nombre' => 'Cenefa', 'consecutivo' => 4],
        ['sku_grupo' => 'CAECM-05', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 56, 'nombre' => 'Repisa Tipo L', 'consecutivo' => 5],
        ['sku_grupo' => 'CAEES-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 57, 'nombre' => '2 Puertas Con Escurreplato', 'consecutivo' => 1],
        ['sku_grupo' => 'CAEES-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 57, 'nombre' => '2 Puertas Con Modulo Abierto Abajo', 'consecutivo' => 2],
        ['sku_grupo' => 'CAEES-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 57, 'nombre' => '1 Puerta Con Escurreplato Izquierdo', 'consecutivo' => 3],
        ['sku_grupo' => 'CAEES-04', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 57, 'nombre' => '1 Puerta Con Escurreplato Derecho', 'consecutivo' => 4],
        ['sku_grupo' => 'CAEEQ-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 58, 'nombre' => 'Esquina Abierto', 'consecutivo' => 1],
        ['sku_grupo' => 'CAENV-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 59, 'nombre' => '1 Puerta Horizontal Para Nevera', 'consecutivo' => 1],
        ['sku_grupo' => 'CAENV-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 59, 'nombre' => '2 Puertas Vertical Para Nevera', 'consecutivo' => 2],
        ['sku_grupo' => 'CAENV-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 59, 'nombre' => 'Panel De Nevera Altura 2220', 'consecutivo' => 3],
        ['sku_grupo' => 'CAEPT-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Derecho', 'consecutivo' => 1],
        ['sku_grupo' => 'CAEPT-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Izquierdo', 'consecutivo' => 2],
        ['sku_grupo' => 'CAEPT-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '1 Puerta Derecho', 'consecutivo' => 3],
        ['sku_grupo' => 'CAEPT-04', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '1 Puerta Horizontal', 'consecutivo' => 4],
        ['sku_grupo' => 'CAEPT-05', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '1 Puerta Izquierdo', 'consecutivo' => 5],
        ['sku_grupo' => 'CAEPT-06', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '2 Puertas', 'consecutivo' => 6],
        ['sku_grupo' => 'CAEPT-07', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 55, 'nombre' => '2 Puertas Horizontal', 'consecutivo' => 7],
        ['sku_grupo' => 'CAEVI-01', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 60, 'nombre' => 'Vinera 14 Espacios ', 'consecutivo' => 1],
        ['sku_grupo' => 'CAEVI-02', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 60, 'nombre' => 'Vinera 21 Espacios', 'consecutivo' => 2],
        ['sku_grupo' => 'CAEVI-03', 'tipo_id' => 6, 'subtipo_id' => 16, 'categoria_id' => 60, 'nombre' => 'Vinera 7 Espacios', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAAB-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Y 2 Repisas', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAAB-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Divisiones Y 3 Repisas', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAAB-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Repisa', 'consecutivo' => 1],
        ['sku_grupo' => 'CBACM-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 1],
        ['sku_grupo' => 'CBACM-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 56, 'nombre' => 'Panel Canteado', 'consecutivo' => 2],
        ['sku_grupo' => 'CBACM-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 56, 'nombre' => 'Panel Cierre A Modulo', 'consecutivo' => 3],
        ['sku_grupo' => 'CBACM-04', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 56, 'nombre' => 'Panel Cierre A Piso', 'consecutivo' => 4],
        ['sku_grupo' => 'CBACM-05', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 56, 'nombre' => 'Panel Especial', 'consecutivo' => 5],
        ['sku_grupo' => 'CBAES-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 57, 'nombre' => 'Condimentero', 'consecutivo' => 1],
        ['sku_grupo' => 'CBAES-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 57, 'nombre' => 'Horno Empotrado', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAES-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 57, 'nombre' => 'Lavaplato Automatico', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAES-04', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 57, 'nombre' => 'Papelera', 'consecutivo' => 4],
        ['sku_grupo' => 'CBAFR-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 63, 'nombre' => 'Fregador 1 Puerta Derecho', 'consecutivo' => 1],
        ['sku_grupo' => 'CBAFR-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 63, 'nombre' => 'Fregador 1 Puerta Izquierdo', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAFR-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 63, 'nombre' => 'Fregador 2 Puertas', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAGV-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 53, 'nombre' => '2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'CBAGV-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 53, 'nombre' => '3 Gavetas 2 Pequeñas Y 1 Grande', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAGV-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 53, 'nombre' => '3 Gavetas', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAGV-04', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 53, 'nombre' => '4 Gavetas', 'consecutivo' => 4],
        ['sku_grupo' => 'CGAGG-01', 'tipo_id' => 6, 'subtipo_id' => 19, 'categoria_id' => 62, 'nombre' => 'Gaveta 256 Full Extension', 'consecutivo' => 1],
        ['sku_grupo' => 'CGAGG-02', 'tipo_id' => 6, 'subtipo_id' => 19, 'categoria_id' => 62, 'nombre' => 'Gaveta 256 Undermount', 'consecutivo' => 2],
        ['sku_grupo' => 'CGAGP-01', 'tipo_id' => 6, 'subtipo_id' => 19, 'categoria_id' => 61, 'nombre' => 'Gaveta 96 Full Extension', 'consecutivo' => 1],
        ['sku_grupo' => 'CGAGP-02', 'tipo_id' => 6, 'subtipo_id' => 19, 'categoria_id' => 61, 'nombre' => 'Gaveta 96 Undermount', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAPT-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Derecho', 'consecutivo' => 1],
        ['sku_grupo' => 'CBAPT-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Izquierdo', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAPT-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => '1 Puerta Derecho', 'consecutivo' => 3],
        ['sku_grupo' => 'CBAPT-04', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => '1 Puerta Izquierdo', 'consecutivo' => 4],
        ['sku_grupo' => 'CBAPT-05', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => '2 Puertas', 'consecutivo' => 5],
        ['sku_grupo' => 'CBAPT-06', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => 'Condimentero', 'consecutivo' => 6],
        ['sku_grupo' => 'CBAVI-01', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 60, 'nombre' => 'Vinera 14 Espacios ', 'consecutivo' => 1],
        ['sku_grupo' => 'CBAVI-02', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 60, 'nombre' => 'Vinera 21 Espacios', 'consecutivo' => 2],
        ['sku_grupo' => 'CBAVI-03', 'tipo_id' => 6, 'subtipo_id' => 17, 'categoria_id' => 60, 'nombre' => 'Vinera 7 Espacios', 'consecutivo' => 3],
        ['sku_grupo' => 'CTOAB-01', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Y 8 Repisas', 'consecutivo' => 1],
        ['sku_grupo' => 'CTOAB-02', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto 1 Division Y 10 Repisas', 'consecutivo' => 2],
        ['sku_grupo' => 'CTOAB-03', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Divisiones Y 12 Repisas', 'consecutivo' => 3],
        ['sku_grupo' => 'CTOAB-04', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto 2 Divisiones Y 15 Repisas', 'consecutivo' => 4],
        ['sku_grupo' => 'CTOAB-05', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto Y 7 Repisas', 'consecutivo' => 5],
        ['sku_grupo' => 'CTOAB-06', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto Y 5 Repisas', 'consecutivo' => 6],
        ['sku_grupo' => 'CTOAB-07', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 52, 'nombre' => 'Abierto Y 4 Repisas', 'consecutivo' => 7],
        ['sku_grupo' => 'CTOCM-01', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 1],
        ['sku_grupo' => 'CTOCM-02', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 56, 'nombre' => 'Panel Canteado', 'consecutivo' => 2],
        ['sku_grupo' => 'CTOCM-03', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 56, 'nombre' => 'Panel Cierre A Modulo', 'consecutivo' => 3],
        ['sku_grupo' => 'CTOCM-04', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 56, 'nombre' => 'Panel Cierre A Piso', 'consecutivo' => 4],
        ['sku_grupo' => 'CTOPT-01', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Derecho', 'consecutivo' => 1],
        ['sku_grupo' => 'CTOPT-02', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '1 Puerta De Esquina Izquierdo', 'consecutivo' => 2],
        ['sku_grupo' => 'CTOPT-03', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '1 Puerta Derecho', 'consecutivo' => 3],
        ['sku_grupo' => 'CTOPT-04', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '1 Puerta Izquierdo', 'consecutivo' => 4],
        ['sku_grupo' => 'CTOPT-05', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '2 Puertas', 'consecutivo' => 5],
        ['sku_grupo' => 'CTOPT-06', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 55, 'nombre' => '4 Puertas', 'consecutivo' => 6],
        ['sku_grupo' => 'CTOSP-01', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => '2 Hornos De 60Cm Para Torre 1 Puerta', 'consecutivo' => 1],
        ['sku_grupo' => 'CTOSP-02', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => '2 Hornos Para Torre 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'CTOSP-03', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Caja Abierta Y 1 Puerta Vertical ', 'consecutivo' => 3],
        ['sku_grupo' => 'CTOSP-04', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Caja Abierta Y 2 Puertas Vertical', 'consecutivo' => 4],
        ['sku_grupo' => 'CTOSP-05', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Horno De 60Cm Para Torre 1 Puerta ', 'consecutivo' => 5],
        ['sku_grupo' => 'CTOSP-06', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Horno De 60Cm Y Microonda Para Torre 1 Puerta Horizontal', 'consecutivo' => 6],
        ['sku_grupo' => 'CTOSP-07', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Horno Empotrado Para Torre 2 Puertas', 'consecutivo' => 7],
        ['sku_grupo' => 'CTOSP-08', 'tipo_id' => 6, 'subtipo_id' => 18, 'categoria_id' => 64, 'nombre' => 'Horno Y Microonda Para Torre 2 Puertas', 'consecutivo' => 8],
        ['sku_grupo' => 'OECST-01', 'tipo_id' => 7, 'subtipo_id' => 21, 'categoria_id' => 66, 'nombre' => 'Escritorio Chiriqui', 'consecutivo' => 1],
        ['sku_grupo' => 'OEXST-01', 'tipo_id' => 7, 'subtipo_id' => 22, 'categoria_id' => 66, 'nombre' => 'Extension Chiriqui', 'consecutivo' => 1],
        ['sku_grupo' => 'BASGD-01', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 67, 'nombre' => 'Artslim 120 2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BASGD-02', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 67, 'nombre' => 'Artslim 120 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'BASGD-03', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 67, 'nombre' => 'Artslim 120 4 Gavetas', 'consecutivo' => 3],
        ['sku_grupo' => 'BASMD-01', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 68, 'nombre' => 'Artslim 90 2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BASMD-02', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 68, 'nombre' => 'Artslim 90 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'BASPQ-01', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 69, 'nombre' => 'Artslim 60 2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BASPQ-02', 'tipo_id' => 8, 'subtipo_id' => 23, 'categoria_id' => 69, 'nombre' => 'Artslim 60 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'BDWMD-01', 'tipo_id' => 8, 'subtipo_id' => 24, 'categoria_id' => 68, 'nombre' => 'Domo Wide 80 2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BDWMD-02', 'tipo_id' => 8, 'subtipo_id' => 24, 'categoria_id' => 68, 'nombre' => 'Domo Wide 80 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'BDWPQ-01', 'tipo_id' => 8, 'subtipo_id' => 24, 'categoria_id' => 69, 'nombre' => 'Domo Wide 60 2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BDWPQ-02', 'tipo_id' => 8, 'subtipo_id' => 24, 'categoria_id' => 69, 'nombre' => 'Domo Wide 60 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'BMDCM-01', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 1],
        ['sku_grupo' => 'BMDCM-02', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 56, 'nombre' => 'Panel Cierre', 'consecutivo' => 2],
        ['sku_grupo' => 'BMDGV-01', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 53, 'nombre' => '2 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'BMDGV-02', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 53, 'nombre' => '3 Gavetas', 'consecutivo' => 2],
        ['sku_grupo' => 'BMDPT-01', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 55, 'nombre' => '1 Puerta Derecho', 'consecutivo' => 1],
        ['sku_grupo' => 'BMDPT-02', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 55, 'nombre' => '1 Puerta Izquierdo', 'consecutivo' => 2],
        ['sku_grupo' => 'BMDPT-03', 'tipo_id' => 8, 'subtipo_id' => 25, 'categoria_id' => 55, 'nombre' => '2 Puertas', 'consecutivo' => 3],
        ['sku_grupo' => 'MGVST-01', 'tipo_id' => 9, 'subtipo_id' => 29, 'categoria_id' => 66, 'nombre' => 'Almirante', 'consecutivo' => 1],
        ['sku_grupo' => 'MGVST-02', 'tipo_id' => 9, 'subtipo_id' => 29, 'categoria_id' => 66, 'nombre' => 'Burari', 'consecutivo' => 2],
        ['sku_grupo' => 'MGVST-03', 'tipo_id' => 9, 'subtipo_id' => 29, 'categoria_id' => 66, 'nombre' => 'Bogola', 'consecutivo' => 3],
        ['sku_grupo' => 'MMNST-01', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Creek', 'consecutivo' => 1],
        ['sku_grupo' => 'MMNST-02', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Toro', 'consecutivo' => 2],
        ['sku_grupo' => 'MMNST-03', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Nargana', 'consecutivo' => 3],
        ['sku_grupo' => 'MMNST-04', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Porvenir', 'consecutivo' => 4],
        ['sku_grupo' => 'MMNST-05', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Guanidup', 'consecutivo' => 5],
        ['sku_grupo' => 'MMNST-06', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Yandup', 'consecutivo' => 6],
        ['sku_grupo' => 'MMNST-07', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Gatun', 'consecutivo' => 7],
        ['sku_grupo' => 'MMNST-08', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Pachequilla', 'consecutivo' => 8],
        ['sku_grupo' => 'MMNST-09', 'tipo_id' => 9, 'subtipo_id' => 27, 'categoria_id' => 66, 'nombre' => 'Rompio', 'consecutivo' => 9],
        ['sku_grupo' => 'SBIST-01', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Paterson', 'consecutivo' => 1],
        ['sku_grupo' => 'SBIST-02', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Kusa', 'consecutivo' => 2],
        ['sku_grupo' => 'SBIST-03', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Kusapin', 'consecutivo' => 3],
        ['sku_grupo' => 'SBIST-04', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Gandoca', 'consecutivo' => 4],
        ['sku_grupo' => 'SBIST-05', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Tole', 'consecutivo' => 5],
        ['sku_grupo' => 'SBIST-06', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Coiba', 'consecutivo' => 6],
        ['sku_grupo' => 'SBIST-07', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Contadora', 'consecutivo' => 7],
        ['sku_grupo' => 'SBIST-08', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Cebaco', 'consecutivo' => 8],
        ['sku_grupo' => 'SBIST-09', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Taborcillo', 'consecutivo' => 9],
        ['sku_grupo' => 'SBIST-10', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Otoque', 'consecutivo' => 10],
        ['sku_grupo' => 'SBIST-11', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Saboga', 'consecutivo' => 11],
        ['sku_grupo' => 'SBIST-12', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Chagres', 'consecutivo' => 12],
        ['sku_grupo' => 'SBIST-13', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Sixaola', 'consecutivo' => 13],
        ['sku_grupo' => 'SBIST-14', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Tuira', 'consecutivo' => 14],
        ['sku_grupo' => 'SBIST-15', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Bayano', 'consecutivo' => 15],
        ['sku_grupo' => 'SBIST-16', 'tipo_id' => 10, 'subtipo_id' => 32, 'categoria_id' => 66, 'nombre' => 'Tabasara', 'consecutivo' => 16],
        ['sku_grupo' => 'SBUST-01', 'tipo_id' => 10, 'subtipo_id' => 33, 'categoria_id' => 66, 'nombre' => 'Buena Vista', 'consecutivo' => 1],
        ['sku_grupo' => 'SBUST-02', 'tipo_id' => 10, 'subtipo_id' => 33, 'categoria_id' => 66, 'nombre' => 'Tobobe', 'consecutivo' => 2],
        ['sku_grupo' => 'SBUST-03', 'tipo_id' => 10, 'subtipo_id' => 33, 'categoria_id' => 66, 'nombre' => 'Bagui', 'consecutivo' => 3],
        ['sku_grupo' => 'SBUST-04', 'tipo_id' => 10, 'subtipo_id' => 33, 'categoria_id' => 66, 'nombre' => 'Carenero', 'consecutivo' => 4],
        ['sku_grupo' => 'SMCST-01', 'tipo_id' => 10, 'subtipo_id' => 34, 'categoria_id' => 66, 'nombre' => 'Chucunaque', 'consecutivo' => 1],
        ['sku_grupo' => 'SMCST-02', 'tipo_id' => 10, 'subtipo_id' => 34, 'categoria_id' => 66, 'nombre' => 'Fortuna', 'consecutivo' => 2],
        ['sku_grupo' => 'SMCST-03', 'tipo_id' => 10, 'subtipo_id' => 34, 'categoria_id' => 66, 'nombre' => 'Red Frog', 'consecutivo' => 3],
        ['sku_grupo' => 'SMCST-04', 'tipo_id' => 10, 'subtipo_id' => 34, 'categoria_id' => 66, 'nombre' => 'Sabanitas', 'consecutivo' => 4],
        ['sku_grupo' => 'STVST-01', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Itamut', 'consecutivo' => 1],
        ['sku_grupo' => 'STVST-02', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Polo', 'consecutivo' => 2],
        ['sku_grupo' => 'STVST-03', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Manzanillo', 'consecutivo' => 3],
        ['sku_grupo' => 'STVST-04', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Drago', 'consecutivo' => 4],
        ['sku_grupo' => 'STVST-05', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Solarte', 'consecutivo' => 5],
        ['sku_grupo' => 'STVST-06', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Bastimento', 'consecutivo' => 6],
        ['sku_grupo' => 'STVST-07', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Veracruz', 'consecutivo' => 7],
        ['sku_grupo' => 'STVST-08', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Ensenada', 'consecutivo' => 8],
        ['sku_grupo' => 'STVST-09', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Estrellas', 'consecutivo' => 9],
        ['sku_grupo' => 'STVST-10', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Farallon', 'consecutivo' => 10],
        ['sku_grupo' => 'STVST-11', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Lajas', 'consecutivo' => 11],
        ['sku_grupo' => 'STVST-12', 'tipo_id' => 10, 'subtipo_id' => 31, 'categoria_id' => 66, 'nombre' => 'Guaira', 'consecutivo' => 12],
        ['sku_grupo' => 'FBAPT-01', 'tipo_id' => 11, 'subtipo_id' => 17, 'categoria_id' => 55, 'nombre' => 'Modulo 1 Puerta Basurero', 'consecutivo' => 1],
        ['sku_grupo' => 'FESCM-01', 'tipo_id' => 11, 'subtipo_id' => 30, 'categoria_id' => 56, 'nombre' => 'Estante Tipo L', 'consecutivo' => 1],
        ['sku_grupo' => 'FMFST-01', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Tortuguilla', 'consecutivo' => 1],
        ['sku_grupo' => 'FMFST-02', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Catalina', 'consecutivo' => 2],
        ['sku_grupo' => 'FMFST-03', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Jaque', 'consecutivo' => 3],
        ['sku_grupo' => 'FMFST-04', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Estero', 'consecutivo' => 4],
        ['sku_grupo' => 'FMFST-05', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Kobbe', 'consecutivo' => 5],
        ['sku_grupo' => 'FMFST-06', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Farfan', 'consecutivo' => 6],
        ['sku_grupo' => 'FMFST-07', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'San Miguel', 'consecutivo' => 7],
        ['sku_grupo' => 'FMFST-08', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Pearl ', 'consecutivo' => 8],
        ['sku_grupo' => 'FMFST-09', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Hermita', 'consecutivo' => 9],
        ['sku_grupo' => 'FMFST-10', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Barqueta', 'consecutivo' => 10],
        ['sku_grupo' => 'FMFST-11', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Malibu', 'consecutivo' => 11],
        ['sku_grupo' => 'FMFST-12', 'tipo_id' => 11, 'subtipo_id' => 35, 'categoria_id' => 66, 'nombre' => 'Taboga', 'consecutivo' => 12],
        ['sku_grupo' => 'QTFHR-01', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 72, 'nombre' => 'Techo Flotante Horizontal Prof 2400mm', 'consecutivo' => 1],
        ['sku_grupo' => 'QTFHR-02', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 72, 'nombre' => 'Techo Flotante Horizontal Prof 1200mm', 'consecutivo' => 2],
        ['sku_grupo' => 'QTFHR-03', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 72, 'nombre' => 'Techo Flotante Horizontal Prof 600mm', 'consecutivo' => 3],
        ['sku_grupo' => 'QTFVT-01', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 73, 'nombre' => 'Techo Flotante Vertical Prof 2400mm', 'consecutivo' => 1],
        ['sku_grupo' => 'QTFVT-02', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 73, 'nombre' => 'Techo Flotante Vertical Prof 1200mm', 'consecutivo' => 2],
        ['sku_grupo' => 'QTFVT-03', 'tipo_id' => 12, 'subtipo_id' => 36, 'categoria_id' => 73, 'nombre' => 'Techo Flotante Vertical Prof 600mm', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLAB-01', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 52, 'nombre' => '5 Repisas (960) Hueco Inferior Con 2 Puertas', 'consecutivo' => 1],
        ['sku_grupo' => 'RCLAB-02', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 52, 'nombre' => '5 Repisas (960) Hueco Inferior Con Puerta Derecha', 'consecutivo' => 2],
        ['sku_grupo' => 'RCLAB-03', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 52, 'nombre' => '5 Repisas (960) Hueco Inferior Con Puerta Izquierda', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLCM-01', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 1],
        ['sku_grupo' => 'RCLCM-02', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 56, 'nombre' => 'Panel Canteado', 'consecutivo' => 2],
        ['sku_grupo' => 'RCLCM-03', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 56, 'nombre' => 'Panel Cierre A Piso', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLCM-04', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 56, 'nombre' => 'Panel Inicial Izquierdo', 'consecutivo' => 4],
        ['sku_grupo' => 'RCLCM-05', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 56, 'nombre' => 'Zocalo', 'consecutivo' => 5],
        ['sku_grupo' => 'RCLGV-01', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 320 1 Gaveta 320 Full Extension', 'consecutivo' => 1],
        ['sku_grupo' => 'RCLGV-02', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 320 1 Gaveta 320 Undermount', 'consecutivo' => 2],
        ['sku_grupo' => 'RCLGV-03', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 320 2 Gavetas 160 Full Extension', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLGV-04', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 320 2 Gavetas 160 Undermount', 'consecutivo' => 4],
        ['sku_grupo' => 'RCLGV-05', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 1 Gaveta 320 Y 2 De 160 Full Extension', 'consecutivo' => 5],
        ['sku_grupo' => 'RCLGV-06', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 1 Gaveta 320 Y 2 De 160 Undermount', 'consecutivo' => 6],
        ['sku_grupo' => 'RCLGV-07', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 2 Gavetas 320 Full Extension', 'consecutivo' => 7],
        ['sku_grupo' => 'RCLGV-08', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 2 Gavetas 320 Undermount', 'consecutivo' => 8],
        ['sku_grupo' => 'RCLGV-09', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 4 Gavetas 160 Full Extension', 'consecutivo' => 9],
        ['sku_grupo' => 'RCLGV-10', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 640 4 Gavetas 160 Undermount', 'consecutivo' => 10],
        ['sku_grupo' => 'RCLGV-11', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 1 Gaveta 320 Y 4 De 160 Full Extension', 'consecutivo' => 11],
        ['sku_grupo' => 'RCLGV-12', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 1 Gaveta 320 Y 4 De 160 Undermount', 'consecutivo' => 12],
        ['sku_grupo' => 'RCLGV-13', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 2 Gavetas 320 Y 2 De 160 Full Extension', 'consecutivo' => 13],
        ['sku_grupo' => 'RCLGV-14', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 2 Gavetas 320 Y 2 De 160 Undermount', 'consecutivo' => 14],
        ['sku_grupo' => 'RCLGV-15', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 3 Gavetas 320 Full Extension', 'consecutivo' => 15],
        ['sku_grupo' => 'RCLGV-16', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 3 Gavetas 320 Undermount', 'consecutivo' => 16],
        ['sku_grupo' => 'RCLGV-17', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 Y 3 Gavetas Zapatera Full Extension', 'consecutivo' => 17],
        ['sku_grupo' => 'RCLGV-18', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 53, 'nombre' => 'Caja 960 Y 3 Gavetas Zapatera Undermount', 'consecutivo' => 18],
        ['sku_grupo' => 'RCLPT-01', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 55, 'nombre' => '7 Repisas Con 2 Puertas', 'consecutivo' => 1],
        ['sku_grupo' => 'RCLPT-02', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 55, 'nombre' => '7 Repisas Con Puerta Derecha', 'consecutivo' => 2],
        ['sku_grupo' => 'RCLPT-03', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 55, 'nombre' => '7 Repisas Con Puerta Izquierda', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLTB-01', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '1 Tubo 2 Puertas 4 Gavetas', 'consecutivo' => 1],
        ['sku_grupo' => 'RCLTB-02', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo Con 2 Puertas', 'consecutivo' => 2],
        ['sku_grupo' => 'RCLTB-03', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo Con Puerta Derecha', 'consecutivo' => 3],
        ['sku_grupo' => 'RCLTB-04', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo Con Puerta Izquierda ', 'consecutivo' => 4],
        ['sku_grupo' => 'RCLTB-05', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (320) Con 2 Puertas', 'consecutivo' => 5],
        ['sku_grupo' => 'RCLTB-06', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (320) Con Puerta Derecha', 'consecutivo' => 6],
        ['sku_grupo' => 'RCLTB-07', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (320) Con Puerta Izquierda', 'consecutivo' => 7],
        ['sku_grupo' => 'RCLTB-08', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640) Con 2 Puertas', 'consecutivo' => 8],
        ['sku_grupo' => 'RCLTB-09', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640) Con Puerta Derecha', 'consecutivo' => 9],
        ['sku_grupo' => 'RCLTB-10', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640) Con Puerta Izquierda', 'consecutivo' => 10],
        ['sku_grupo' => 'RCLTB-11', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (960) Con 2 Puertas', 'consecutivo' => 11],
        ['sku_grupo' => 'RCLTB-12', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (960) Con Puerta Derecha', 'consecutivo' => 12],
        ['sku_grupo' => 'RCLTB-13', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (960) Con Puerta Izquierda', 'consecutivo' => 13],
        ['sku_grupo' => 'RCLTB-14', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos Con 2 Puertas', 'consecutivo' => 14],
        ['sku_grupo' => 'RCLTB-15', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos Con Puerta Derecha', 'consecutivo' => 15],
        ['sku_grupo' => 'RCLTB-16', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos Con Puerta Izquierda', 'consecutivo' => 16],
        ['sku_grupo' => 'RCLTB-17', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960) Con 2 Puertas', 'consecutivo' => 17],
        ['sku_grupo' => 'RCLTB-18', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960) Con Puerta Derecha', 'consecutivo' => 18],
        ['sku_grupo' => 'RCLTB-19', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960) Con Puerta Izquierda', 'consecutivo' => 19],
        ['sku_grupo' => 'RCLTB-20', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Inferior Con 2 Puertas', 'consecutivo' => 20],
        ['sku_grupo' => 'RCLTB-21', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Inferior Con Puerta Derecha', 'consecutivo' => 21],
        ['sku_grupo' => 'RCLTB-22', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Inferior Con Puerta Izquierda', 'consecutivo' => 22],
        ['sku_grupo' => 'RCLTB-23', 'tipo_id' => 13, 'subtipo_id' => 38, 'categoria_id' => 75, 'nombre' => '2 Tubos 2 Puertas 4 Gavetas 3 Repisas', 'consecutivo' => 23],
        ['sku_grupo' => 'RVEAB-01', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 52, 'nombre' => '5 Repisas (960) Hueco Inferior', 'consecutivo' => 1],
        ['sku_grupo' => 'RVEAB-02', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 52, 'nombre' => '7 Repisas', 'consecutivo' => 2],
        ['sku_grupo' => 'RVEAB-03', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 52, 'nombre' => '7 Repisas Esquina Izquierda', 'consecutivo' => 3],
        ['sku_grupo' => 'RVEAB-04', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 52, 'nombre' => '7 Repisas Esquina Derecha', 'consecutivo' => 4],
        ['sku_grupo' => 'RVECM-01', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 56, 'nombre' => 'Fondo 15mm', 'consecutivo' => 1],
        ['sku_grupo' => 'RVECM-02', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 56, 'nombre' => 'Fondo Delgado', 'consecutivo' => 2],
        ['sku_grupo' => 'RVECM-03', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 56, 'nombre' => 'Jamba', 'consecutivo' => 3],
        ['sku_grupo' => 'RVECM-04', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 56, 'nombre' => 'Panel Canteado', 'consecutivo' => 4],
        ['sku_grupo' => 'RVECM-05', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 56, 'nombre' => 'Panel Inicial Izquierdo', 'consecutivo' => 5],
        ['sku_grupo' => 'RVEGV-01', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 320 1 Gaveta 320 Full Extension', 'consecutivo' => 1],
        ['sku_grupo' => 'RVEGV-02', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 320 1 Gaveta 320 Undermount', 'consecutivo' => 2],
        ['sku_grupo' => 'RVEGV-03', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 320 2 Gavetas 160 Full Extension', 'consecutivo' => 3],
        ['sku_grupo' => 'RVEGV-04', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 320 2 Gavetas 160 Undermount', 'consecutivo' => 4],
        ['sku_grupo' => 'RVEGV-05', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 320 Con Puerta', 'consecutivo' => 5],
        ['sku_grupo' => 'RVEGV-06', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 1 Gaveta 320 Y 2 De 160 Full Extension', 'consecutivo' => 6],
        ['sku_grupo' => 'RVEGV-07', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 1 Gaveta 320 Y 2 De 160 Undermount', 'consecutivo' => 7],
        ['sku_grupo' => 'RVEGV-08', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 2 Gavetas 320 Full Extension', 'consecutivo' => 8],
        ['sku_grupo' => 'RVEGV-09', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 2 Gavetas 320 Undermount', 'consecutivo' => 9],
        ['sku_grupo' => 'RVEGV-10', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 4 Gavetas 160 Full Extension', 'consecutivo' => 10],
        ['sku_grupo' => 'RVEGV-11', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 4 Gavetas 160 Undermount', 'consecutivo' => 11],
        ['sku_grupo' => 'RVEGV-12', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 640 Con Puerta', 'consecutivo' => 12],
        ['sku_grupo' => 'RVEGV-13', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 1 Gaveta 320 Y 4 De 160 Full Extension', 'consecutivo' => 13],
        ['sku_grupo' => 'RVEGV-14', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 1 Gaveta 320 Y 4 De 160 Undermount', 'consecutivo' => 14],
        ['sku_grupo' => 'RVEGV-15', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 2 Gavetas 320 Y 2 De 160 Full Extension', 'consecutivo' => 15],
        ['sku_grupo' => 'RVEGV-16', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 2 Gavetas 320 Y 2 De 160 Undermount', 'consecutivo' => 16],
        ['sku_grupo' => 'RVEGV-17', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 3 Gavetas 320 Full Extension', 'consecutivo' => 17],
        ['sku_grupo' => 'RVEGV-18', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 3 Gavetas 320 Undermount', 'consecutivo' => 18],
        ['sku_grupo' => 'RVEGV-19', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 Con Puerta', 'consecutivo' => 19],
        ['sku_grupo' => 'RVEGV-20', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 Y 3 Gavetas Zapatera Full Extension', 'consecutivo' => 20],
        ['sku_grupo' => 'RVEGV-21', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 53, 'nombre' => 'Caja 960 Y 3 Gavetas Zapatera Undermount', 'consecutivo' => 21],
        ['sku_grupo' => 'RVEAB-05', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 52, 'nombre' => 'Caja 2400 Y 5 Repisas', 'consecutivo' => 5],
        ['sku_grupo' => 'RVETB-01', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo', 'consecutivo' => 1],
        ['sku_grupo' => 'RVETB-02', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo Esquina Derecha', 'consecutivo' => 2],
        ['sku_grupo' => 'RVETB-03', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '2 Repisas 1 Tubo Esquina Izquierda', 'consecutivo' => 3],
        ['sku_grupo' => 'RVETB-04', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640)', 'consecutivo' => 4],
        ['sku_grupo' => 'RVETB-05', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640) Esquina Izquierda', 'consecutivo' => 5],
        ['sku_grupo' => 'RVETB-06', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (640) Esquina Derecha', 'consecutivo' => 6],
        ['sku_grupo' => 'RVETB-07', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubo (960)', 'consecutivo' => 7],
        ['sku_grupo' => 'RVETB-08', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubos (320)', 'consecutivo' => 8],
        ['sku_grupo' => 'RVETB-09', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubos (320) Esquina Izquierda', 'consecutivo' => 9],
        ['sku_grupo' => 'RVETB-10', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 1 Tubos (320) Esquina Derecha', 'consecutivo' => 10],
        ['sku_grupo' => 'RVETB-11', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos', 'consecutivo' => 11],
        ['sku_grupo' => 'RVETB-12', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos Esquina Izquierda', 'consecutivo' => 12],
        ['sku_grupo' => 'RVETB-13', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '3 Repisas 2 Tubos Esquina Derecha', 'consecutivo' => 13],
        ['sku_grupo' => 'RVETB-14', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/640)', 'consecutivo' => 14],
        ['sku_grupo' => 'RVETB-15', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/640) Esquina Izquierda', 'consecutivo' => 15],
        ['sku_grupo' => 'RVETB-16', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/640) Esquina Derecha', 'consecutivo' => 16],
        ['sku_grupo' => 'RVETB-17', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960)', 'consecutivo' => 17],
        ['sku_grupo' => 'RVETB-18', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960) Esquina Derecha', 'consecutivo' => 18],
        ['sku_grupo' => 'RVETB-19', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '4 Repisas 1 Tubo (320/960) Esquina Izquierda', 'consecutivo' => 19],
        ['sku_grupo' => 'RVETB-20', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (320/640/960) 1 Tubo Superior', 'consecutivo' => 20],
        ['sku_grupo' => 'RVETB-21', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (320/640/960) 1 Tubo Superior Esquina Derecha', 'consecutivo' => 21],
        ['sku_grupo' => 'RVETB-22', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (320/640/960) 1 Tubo Superior Esquina Izquierda', 'consecutivo' => 22],
        ['sku_grupo' => 'RVETB-23', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Esquina Izquierda', 'consecutivo' => 23],
        ['sku_grupo' => 'RVETB-24', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Esquina Derecha', 'consecutivo' => 24],
        ['sku_grupo' => 'RVETB-25', 'tipo_id' => 13, 'subtipo_id' => 39, 'categoria_id' => 75, 'nombre' => '5 Repisas (960) 1 Tubo Inferior', 'consecutivo' => 25]
    ]
);

foreach ( $modulos as $obj) {
  $modulo = new Modulo;
  $modulo->sku_grupo = $obj['sku_grupo'];
  $modulo->tipo_id = $obj['tipo_id'];
  $modulo->subtipo_id = $obj['subtipo_id'];
  $modulo->categoria_id = $obj['categoria_id'];
  $modulo->nombre = $obj['nombre'];
  $modulo->consecutivo = $obj['consecutivo'];
  $modulo->save();
}

}

}

