<?php

use Illuminate\Database\Seeder;
use App\Tablero;

class TablerosSeeder extends Seeder
{

  public function run()
  {
    $tableros = collect([
      [
        "id" => 1,
        "categoria_id" => 13,
        "colore_id" => 1,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 2,
        "categoria_id" => 13,
        "colore_id" => 2,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 3,
        "categoria_id" => 13,
        "colore_id" => 5,
        "C4" => NULL,
        "C15" => 10.00,
        "C16" => NULL,
        "C18" => NULL,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 4,
        "categoria_id" => 13,
        "colore_id" => 6,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 5,
        "categoria_id" => 13,
        "colore_id" => 8,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 6,
        "categoria_id" => 13,
        "colore_id" => 9,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 7,
        "categoria_id" => 13,
        "colore_id" => 14,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 8,
        "categoria_id" => 13,
        "colore_id" => 17,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 9,
        "categoria_id" => 13,
        "colore_id" => 18,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 10,
        "categoria_id" => 13,
        "colore_id" => 20,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 11,
        "categoria_id" => 13,
        "colore_id" => 21,
        "C4" => NULL,
        "C15" => 10.00,
        "C16" => NULL,
        "C18" => NULL,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 12,
        "categoria_id" => 13,
        "colore_id" => 22,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 13,
        "categoria_id" => 13,
        "colore_id" => 23,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 14,
        "categoria_id" => 13,
        "colore_id" => 24,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 15,
        "categoria_id" => 13,
        "colore_id" => 25,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 16,
        "categoria_id" => 13,
        "colore_id" => 26,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 17,
        "categoria_id" => 13,
        "colore_id" => 27,
        "C4" => NULL,
        "C15" => 10.00,
        "C16" => NULL,
        "C18" => NULL,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 18,
        "categoria_id" => 13,
        "colore_id" => 4,
        "C4" => NULL,
        "C15" => NULL,
        "C16" => NULL,
        "C18" => 66.00,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 19,
        "categoria_id" => 13,
        "colore_id" => 10,
        "C4" => NULL,
        "C15" => NULL,
        "C16" => NULL,
        "C18" => 66.00,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 20,
        "categoria_id" => 13,
        "colore_id" => 11,
        "C4" => NULL,
        "C15" => NULL,
        "C16" => NULL,
        "C18" => 66.00,
        "C19" => NULL,
        "C25" => NULL,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 21,
        "categoria_id" => 13,
        "colore_id" => 3,
        "C4" => 45.00,
        "C15" => 78.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 16.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 22,
        "categoria_id" => 13,
        "colore_id" => 12,
        "C4" => NULL,
        "C15" => 13.00,
        "C16" => NULL,
        "C18" => 14.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 23,
        "categoria_id" => 13,
        "colore_id" => 13,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 24,
        "categoria_id" => 13,
        "colore_id" => 19,
        "C4" => NULL,
        "C15" => 13.00,
        "C16" => NULL,
        "C18" => 14.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 25,
        "categoria_id" => 13,
        "colore_id" => 7,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 26,
        "categoria_id" => 13,
        "colore_id" => 15,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 27,
        "categoria_id" => 13,
        "colore_id" => 16,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
      [
        "id" => 28,
        "categoria_id" => 13,
        "colore_id" => 28,
        "C4" => NULL,
        "C15" => 14.00,
        "C16" => NULL,
        "C18" => 15.00,
        "C19" => NULL,
        "C25" => 18.00,
        "created_at" => NULL,
        "updated_at" => NULL,
        "deleted_at" => NULL,
      ],
    ]);
  foreach ($tableros as $values) {
        Tablero::create($values);
      }

}
}
