<?php

use Illuminate\Database\Seeder;
use App\Tablero;

class TablerosSeeder extends Seeder
{

  public function run()
  {
    $tableros = collect([
        [
            "id" => 1,
            "categoria_id" => 51,
            "colore_id" => 1,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 2,
            "categoria_id" => 51,
            "colore_id" => 1,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 3,
            "categoria_id" => 51,
            "colore_id" => 1,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 4,
            "categoria_id" => 51,
            "colore_id" => 2,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 5,
            "categoria_id" => 51,
            "colore_id" => 2,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 6,
            "categoria_id" => 51,
            "colore_id" => 2,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 7,
            "categoria_id" => 51,
            "colore_id" => 5,
            "espesor" => "15",
            "costo" => 10.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 8,
            "categoria_id" => 51,
            "colore_id" => 6,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 9,
            "categoria_id" => 51,
            "colore_id" => 6,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 10,
            "categoria_id" => 51,
            "colore_id" => 6,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 11,
            "categoria_id" => 51,
            "colore_id" => 8,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 12,
            "categoria_id" => 51,
            "colore_id" => 8,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 13,
            "categoria_id" => 51,
            "colore_id" => 8,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 14,
            "categoria_id" => 51,
            "colore_id" => 9,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 15,
            "categoria_id" => 51,
            "colore_id" => 9,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 16,
            "categoria_id" => 51,
            "colore_id" => 9,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 17,
            "categoria_id" => 51,
            "colore_id" => 14,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 18,
            "categoria_id" => 51,
            "colore_id" => 14,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 19,
            "categoria_id" => 51,
            "colore_id" => 14,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 20,
            "categoria_id" => 51,
            "colore_id" => 17,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 21,
            "categoria_id" => 51,
            "colore_id" => 17,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 22,
            "categoria_id" => 51,
            "colore_id" => 17,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 23,
            "categoria_id" => 51,
            "colore_id" => 18,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 24,
            "categoria_id" => 51,
            "colore_id" => 18,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 25,
            "categoria_id" => 51,
            "colore_id" => 18,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 26,
            "categoria_id" => 51,
            "colore_id" => 20,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 27,
            "categoria_id" => 51,
            "colore_id" => 20,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 28,
            "categoria_id" => 51,
            "colore_id" => 20,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 29,
            "categoria_id" => 51,
            "colore_id" => 21,
            "espesor" => "15",
            "costo" => 10.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 30,
            "categoria_id" => 51,
            "colore_id" => 22,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 31,
            "categoria_id" => 51,
            "colore_id" => 22,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 32,
            "categoria_id" => 51,
            "colore_id" => 22,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 33,
            "categoria_id" => 51,
            "colore_id" => 23,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 34,
            "categoria_id" => 51,
            "colore_id" => 23,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 35,
            "categoria_id" => 51,
            "colore_id" => 23,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 36,
            "categoria_id" => 51,
            "colore_id" => 24,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 37,
            "categoria_id" => 51,
            "colore_id" => 24,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 38,
            "categoria_id" => 51,
            "colore_id" => 24,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 39,
            "categoria_id" => 51,
            "colore_id" => 25,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 40,
            "categoria_id" => 51,
            "colore_id" => 25,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 41,
            "categoria_id" => 51,
            "colore_id" => 25,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 42,
            "categoria_id" => 51,
            "colore_id" => 26,
            "espesor" => "15",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 43,
            "categoria_id" => 51,
            "colore_id" => 26,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 44,
            "categoria_id" => 51,
            "colore_id" => 26,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 45,
            "categoria_id" => 51,
            "colore_id" => 27,
            "espesor" => "15",
            "costo" => 10.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 46,
            "categoria_id" => 51,
            "colore_id" => 4,
            "espesor" => "18",
            "costo" => 66.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 47,
            "categoria_id" => 51,
            "colore_id" => 10,
            "espesor" => "18",
            "costo" => 66.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 48,
            "categoria_id" => 51,
            "colore_id" => 11,
            "espesor" => "18",
            "costo" => 66.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 49,
            "categoria_id" => 51,
            "colore_id" => 3,
            "espesor" => "4",
            "costo" => 45.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 50,
            "categoria_id" => 51,
            "colore_id" => 3,
            "espesor" => "15",
            "costo" => 78.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 51,
            "categoria_id" => 51,
            "colore_id" => 3,
            "espesor" => "18",
            "costo" => 15.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 52,
            "categoria_id" => 51,
            "colore_id" => 3,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 53,
            "categoria_id" => 51,
            "colore_id" => 12,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 54,
            "categoria_id" => 51,
            "colore_id" => 12,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 55,
            "categoria_id" => 51,
            "colore_id" => 12,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 56,
            "categoria_id" => 51,
            "colore_id" => 13,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 57,
            "categoria_id" => 51,
            "colore_id" => 13,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 58,
            "categoria_id" => 51,
            "colore_id" => 13,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 59,
            "categoria_id" => 51,
            "colore_id" => 19,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 60,
            "categoria_id" => 51,
            "colore_id" => 19,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 61,
            "categoria_id" => 51,
            "colore_id" => 19,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 62,
            "categoria_id" => 51,
            "colore_id" => 7,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 63,
            "categoria_id" => 51,
            "colore_id" => 7,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 64,
            "categoria_id" => 51,
            "colore_id" => 7,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 65,
            "categoria_id" => 51,
            "colore_id" => 15,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 66,
            "categoria_id" => 51,
            "colore_id" => 15,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 67,
            "categoria_id" => 51,
            "colore_id" => 15,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 68,
            "categoria_id" => 51,
            "colore_id" => 16,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 69,
            "categoria_id" => 51,
            "colore_id" => 16,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 70,
            "categoria_id" => 51,
            "colore_id" => 16,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 71,
            "categoria_id" => 51,
            "colore_id" => 28,
            "espesor" => "15",
            "costo" => 13.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 72,
            "categoria_id" => 51,
            "colore_id" => 28,
            "espesor" => "18",
            "costo" => 14.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
        [
            "id" => 73,
            "categoria_id" => 51,
            "colore_id" => 28,
            "espesor" => "25",
            "costo" => 18.00,
            "created_by" => NULL,
            "updated_by" => NULL,
            "approved_by" => NULL,
            "approved_on" => NULL,
            "created_at" => NULL,
            "updated_at" => NULL,
            "deleted_at" => NULL,
        ],
    ]);
$this->command->getOutput()->progressStart(73);
foreach ($tableros as $values) {
    $this->command->getOutput()->progressAdvance();
    Tablero::create($values);
}
$this->command->getOutput()->progressFinish();

}
}
